- name: "Add InfluxDB repository"
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: "{{ telegraf_yum_baseurl[ansible_distribution|lower] | default(telegraf_yum_baseurl['default']) }}"
    gpgcheck: "{{ telegraf_yum_gpgcheck | default('true') }}"
    gpgkey: "{{ telegraf_yum_gpgkey }}"
  become: yes

- name: "Install Telegraf package"
  package:
    name: "{{ telegraf_agent_package }}"
    state: present
  register: is_telegraf_package_installed
  until: is_telegraf_package_installed is succeeded
  become: yes
  notify: "Restart Telegraf"

- name: "Create Telegraf configuration directory"
  file:
    path: "{{ telegraf_agent_config_path }}"
    state: directory
    owner: "{{ telegraf_runas_user }}"
    group: "{{ telegraf_runas_group }}"
    mode: 0755

- name: "Create Telegraf log directory"
  file:
    path: "{{ telegraf_agent_log_path }}"
    state: directory
    owner: "{{ telegraf_runas_user }}"
    group: "{{ telegraf_runas_group }}"
    mode: 0755

- name: "Configuring Telegraf"
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_agent_config_path }}/telegraf.conf"
    owner: "{{ telegraf_runas_user }}"
    group: "{{ telegraf_runas_group }}"
    mode: 0640
  become: yes
  notify: "Restart Telegraf"

- name: "Create Telegraf extra configuration directory"
  file:
    path: "{{ telegraf_agent_config_path }}/telegraf.d"
    state: directory
    owner: "{{ telegraf_runas_user }}"
    group: "{{ telegraf_runas_group }}"
    mode: 0755

- name: "Copy telegraf extra plugins"
  template:
    src: "telegraf-extra-plugin.conf.j2"
    dest: "{{ telegraf_agent_config_path }}/telegraf.d/{{ item.key }}.conf"
    owner: "{{ telegraf_runas_user }}"
    group: "{{ telegraf_runas_group }}"
    mode: 0640
  with_dict: "{{ telegraf_plugins_extra }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - telegraf_plugins_extra is defined
    - telegraf_plugins_extra is iterable
    - item.value.state|default('present') != 'absent'
  become: yes
  notify: "Restart Telegraf"

- name: "Create systemd service unit"
  template:
    src: telegraf.service.j2
    dest: /etc/systemd/system/telegraf.service
    owner: root
    group: root
    mode: 0644
  notify: "Restart Telegraf"
